[server]
addr = "0.0.0.0:3306"
user = "root"
password = "1234"
whitelist = ["127.0.0.1",  "127.0.0.2", "127.0.0.3"]

[[source]]
name = "db1"
type = "mysql"
host = "127.0.0.1"
port = 3306
user = "test"
password = "test"
database = "test"
[[source.view]]
name = "t1"
sql = "select * from test1"
[[source.view]]
name = "t2"
sql = "select * from test2"

[[source]]
name = "db2"
type = "mysql"
host = "127.0.0.1"
port = 3307
user = "test"
password = "test"
database = "test"
[[source.view]]
name = "t1"
sql = "select * from test1"
[[source.view]]
name = "t2"
sql = "select * from test2"

[[source]]
name = "db3"
type = "mysql"
host = "127.0.0.1"
port = 3308
user = "test"
password = "test"
database = "test"
[[source.view]]
name = "t1"
sql = "select * from test1"
[[source.view]]
name = "t2"
sql = "select * from test2"

[[group]]
name = "group1"
source = ["db1", "db2"]

[[group]]
name = "group2"
source = ["db1", "db3"]